Odin JS Weather API Project
kwizl/weather-app pull request #1
Opened 2020-08-18 09:30 UTC by kwizl

# Consuming API
- In this project we are going to create a weather forecast site using the weather API. The should be able to search for a specific location and toggle displaying the data in Fahrenheit or Celsius.

2020-08-22 04:43 UTC, uryelah requested changes
Hi **Martin Njoroge**, I'm Sarah your reviewer for this PR 👩‍🚀 

Good job! Your code is beautifully organized and you've added a very charming button interaction.

Now, you are still missing a couple of core requirements for this project, namely the app look changing according to the received data and the toggle button between Celcius and Fahrenheit.

Check the pointers below and keep on coding! 🏃 💨 

# Required Changes 🏗️ 🐛 💡

- [x] Add a toggle control to determine if the result will be shown in Celsius or Fahrenheit.
![search_requirement](https://user-images.githubusercontent.com/16193212/90948799-d27d5a80-e418-11ea-876e-cb58af940bf3.png)

- [x] Change the app appearance according to the fetched data.

- [ ] [OPTIONAL] Add a loader to show the user while the data is being fetched.

- [ ] [OPTIONAL] If you want a challenge: fetch the current geolocation of the user when the app is first accessed and use that location as the first search when the app is loaded.

-----

 **Kindly fix the pointed out issues and comments below before requesting the next code review**

------------

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

2020-08-22 04:43 UTC, uryelah commented on dist/css/style.css
> +#content {
- [x] Remember CSS good practices, avoid styling elements using ids, prefer classes.

2020-08-22 04:43 UTC, uryelah commented on src/js/models/search.js
> +      display.errorDisplay(error.message);
- [x] Make sure to display a friendly error to the user, set a readable message for when the user tries to search for an inexistent city, at the moment it shows 'e.main is undefined' and 'City: undefined'.

2020-08-22 04:43 UTC, uryelah commented on src/js/views/display.js
> +  const apiData = (data) => {
- [x] Let's also change something visual within the app according to the received data. 
It's a requirement to change the appearance of the app according to the data received, like the background reflecting the weather. 
![appearance_requirement](https://user-images.githubusercontent.com/16193212/90948689-8aaa0380-e417-11ea-87aa-ed6382b40721.png)

2020-08-30 14:47 UTC, rOluochKe approved these changes
Hello @kwizl 
### Good job :clap: The project has been approved. Congratulations :boom: :100:
### Merge and submit the project. Good luck with the next one.
- Happy hacking!

### Optional
- You can write more scripts to automate some of the tasks for you like, see the scripts below
```
"scripts": {
    "dev": "webpack --mode development",
    "build": "webpack --mode production",
    "start": "webpack-dev-server --mode development --open" // optional
  },
```

2020-08-30 15:09 UTC, kwizl commented on src/js/views/display.js
> +  const apiData = (data) => {
Implemented all corrections except the two optional ones. Thanks for the detailed feedback

2020-08-30 15:09 UTC, merged